In [16]:
import numpy as np

inp1 = """<x=-1, y=0, z=2>
<x=2, y=-10, z=-7>
<x=4, y=-8, z=8>
<x=3, y=5, z=-1>"""


def parse_input(inp1):
    lines = inp1.split('\n')
    moons = []
    for line in lines:
        coords = line.split(',')
        moon = []
        for coord in coords:
            coord = coord.replace(' ', '').replace('<', '').replace('>', '')
            moon.append(int(coord.split('=')[1]))
        moons.append(np.array(moon))
    return dict(zip(['Io', 'Europa', 'Ganymede', 'Callisto'], moons))


# moons 'Io', 'Europa', 'Ganymede', 'Callisto'
def step(moons, velocities):
    # update velocities
    for moon in moons:
        x1 = moons[moon]
        v1 = velocities[moon]
        for other_moon in moons:
            if moon != other_moon:
                x2 = moons[other_moon]
                dx = x2 - x1
                v1 += np.sign(dx)
    # update positions
    for moon in moons:
        x1 = moons[moon]
        v1 = velocities[moon]
        x1 += v1
    return moons, velocities


def printout(step, moons, velocities):
    print(f'after {step} steps')
    for moon in moons:
        pos = moons[moon]
        vel = velocities[moon]
        print(f'pos=<x={pos[0]}, y={pos[1]}, z={pos[2]}>, vel=<x={vel[0]}, y={vel[1]}, z={vel[2]}>')
    print(f'total energy: {total_energy(moons, velocities)}')


def total_energy(moons, velocities):
    total = []
    for moon in moons:
        pot = np.sum(np.abs(moons[moon]))
        kin = np.sum(np.abs(velocities[moon]))
        total.append(pot * kin)
    return sum(total)


# unit test part1
moons = parse_input(inp1)
assert np.allclose(moons['Io'], np.array([-1, 0, 2]))
velocities = {key: np.array([0, 0, 0]) for key in moons}
printout(0, moons, velocities)
moons, velocities = step(moons, velocities)
printout(1, moons, velocities)
for _ in range(9):
    moons, velocities = step(moons, velocities)
printout(10, moons, velocities)
assert total_energy(moons, velocities) == 179

# part1
moons = parse_input(open('data/input12').read().strip())
velocities = {key: np.array([0, 0, 0]) for key in moons}
for _ in range(1000):
    moons, velocities = step(moons, velocities)
print(f'solution for part1: {total_energy(moons, velocities)}')

moons = parse_input(open('data/input12').read().strip())
velocities = {key: np.array([0, 0, 0]) for key in moons}
energies = [total_energy(moons, velocities)]
positions = [np.array(list(moons.values()))]
velocities_history = [np.array(list(velocities.values()))]
for _ in range(250):
    moons, velocities = step(moons, velocities)
    energies.append(total_energy(moons, velocities))
    positions.append(np.array(list(moons.values())))
    velocities_history.append(np.array(list(velocities.values())))

after 0 steps
pos=<x=-1, y=0, z=2>, vel=<x=0, y=0, z=0>
pos=<x=2, y=-10, z=-7>, vel=<x=0, y=0, z=0>
pos=<x=4, y=-8, z=8>, vel=<x=0, y=0, z=0>
pos=<x=3, y=5, z=-1>, vel=<x=0, y=0, z=0>
total energy: 0
after 1 steps
pos=<x=2, y=-1, z=1>, vel=<x=3, y=-1, z=-1>
pos=<x=3, y=-7, z=-4>, vel=<x=1, y=3, z=3>
pos=<x=1, y=-7, z=5>, vel=<x=-3, y=1, z=-3>
pos=<x=2, y=2, z=0>, vel=<x=-1, y=-3, z=1>
total energy: 229
after 10 steps
pos=<x=2, y=1, z=-3>, vel=<x=-3, y=-2, z=1>
pos=<x=1, y=-8, z=0>, vel=<x=-1, y=1, z=3>
pos=<x=3, y=-6, z=1>, vel=<x=3, y=2, z=-3>
pos=<x=2, y=0, z=4>, vel=<x=1, y=-1, z=-1>
total energy: 179
solution for part1: 12053


In [17]:
len(positions)

251

In [18]:
len(velocities_history)

251

In [19]:
xyz = np.array([item[0] for item in positions]).astype(np.float)
x, y, z = xyz[:, 0], xyz[:, 1], xyz[:, 2]

In [20]:
import ipyvolume as ipv
import numpy as np

In [22]:
p = ipv.plot(x, y, z)
p2 = ipv.scatter(x, y, z, size=3, marker='sphere')
p.material.linewidth = 20
ipv.show()

Let's plot all four trajectories 

In [7]:
def get_traj(index, positions):
    xyz = np.array([item[index] for item in positions]).astype(np.float)
    x, y, z = xyz[:, 0], xyz[:, 1], xyz[:, 2]
    return x, y, z

In [23]:
colors = ['red', 'green', 'blue', 'black']
ipv.figure()
for index in range(4):
    x, y, z = get_traj(index, positions)
    p = ipv.plot(x, y, z, color=colors[index])
ipv.show()

Avec le barycentre?

In [9]:
xyz = np.array([item.mean(axis=0) for item in positions])
x, y, z = xyz[:, 0], xyz[:, 1], xyz[:, 2]

In [10]:
xyz

array([[6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
       [6.25, 7.75, 5.25],
 

In [11]:
positions[0].mean(axis=0)

array([6.25, 7.75, 5.25])

In [12]:
ipv.figure()
p = ipv.plot(x, y, z, color='black')
ipv.show()

Qui des vitesses ?

In [13]:
colors = ['red', 'green', 'blue', 'black']
ipv.figure()
for index in range(4):
    x, y, z = get_traj(index, velocities_history)
    p = ipv.plot(x, y, z, color=colors[index])
ipv.show()

In [14]:
xyz = np.array([item.mean(axis=0) for item in velocities_history])
x, y, z = xyz[:, 0], xyz[:, 1], xyz[:, 2]

In [15]:
xyz

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0